imports:
    - { resource: services/contexts.yml }
    - { resource: services/pages.yml }
    - { resource: services/elements.yml }

services:
    _defaults:
        public: true

    coreshop.behat.shared_storage:
        class: CoreShop\Behat\Service\SharedStorage

    coreshop.behat.class_storage:
        class: CoreShop\Behat\Service\ClassStorage

    CoreShop\Behat\Service\RelationalIndexExtension:
        tags:
            - { name: coreshop.index.extension }

    CoreShop\Behat\Service\CustomRelationalIndexInterpreter:
        tags:
            - { name: coreshop.index.interpreter, type: custom_relational }

    CoreShop\Behat\Service\Resolver\CurrentPageResolverInterface: '@CoreShop\Behat\Service\Resolver\CurrentPageResolver'
    CoreShop\Behat\Service\Resolver\CurrentPageResolver:
        arguments:
            - '@behat.mink.default_session'
            - '@router'

